services:
  - type: cron
    name: youtube-comment-sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    schedule: "@daily"  # runs once per day at 00:00 UTC
    region: oregon
